# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Miles/Desktop/Interface_Technology/Verilog_1/project_2.srcs/sources_1/bd/swerv_soc/ip/swerv_soc_VGA_v1_0_0_0/swerv_soc_VGA_v1_0_0_0.xci
# IP: The module: 'swerv_soc_VGA_v1_0_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Miles/Desktop/Interface_Technology/Verilog_1/project_2.gen/sources_1/bd/swerv_soc/ip/swerv_soc_VGA_v1_0_0_0/edit_VGA_v1_0.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/Miles/Desktop/Interface_Technology/Verilog_1/project_2.gen/sources_1/bd/swerv_soc/ip/swerv_soc_VGA_v1_0_0_0/edit_VGA_v1_0.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Miles/Desktop/Interface_Technology/Verilog_1/project_2.gen/sources_1/bd/swerv_soc/ip/swerv_soc_VGA_v1_0_0_0/edit_VGA_v1_0.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Miles/Desktop/Interface_Technology/Verilog_1/project_2.gen/sources_1/bd/swerv_soc/ip/swerv_soc_VGA_v1_0_0_0/edit_VGA_v1_0.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc

# IP: C:/Users/Miles/Desktop/Interface_Technology/Verilog_1/project_2.srcs/sources_1/bd/swerv_soc/ip/swerv_soc_VGA_v1_0_0_0/swerv_soc_VGA_v1_0_0_0.xci
# IP: The module: 'swerv_soc_VGA_v1_0_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/Miles/Desktop/Interface_Technology/Verilog_1/project_2.gen/sources_1/bd/swerv_soc/ip/swerv_soc_VGA_v1_0_0_0/edit_VGA_v1_0.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/Miles/Desktop/Interface_Technology/Verilog_1/project_2.gen/sources_1/bd/swerv_soc/ip/swerv_soc_VGA_v1_0_0_0/edit_VGA_v1_0.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Miles/Desktop/Interface_Technology/Verilog_1/project_2.gen/sources_1/bd/swerv_soc/ip/swerv_soc_VGA_v1_0_0_0/edit_VGA_v1_0.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Miles/Desktop/Interface_Technology/Verilog_1/project_2.gen/sources_1/bd/swerv_soc/ip/swerv_soc_VGA_v1_0_0_0/edit_VGA_v1_0.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
