# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/_Code/verilog/interface_lab/RVfpga_SoC_lab7_example/RVfpga_SoC.srcs/sources_1/bd/swerv_soc/ip/swerv_soc_axi_gpio_0_1/swerv_soc_axi_gpio_0_1.xci
# IP: The module: 'swerv_soc_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/_Code/verilog/interface_lab/RVfpga_SoC_lab7_example/RVfpga_SoC.srcs/sources_1/bd/swerv_soc/ip/swerv_soc_axi_gpio_0_1/swerv_soc_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'swerv_soc_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/_Code/verilog/interface_lab/RVfpga_SoC_lab7_example/RVfpga_SoC.srcs/sources_1/bd/swerv_soc/ip/swerv_soc_axi_gpio_0_1/swerv_soc_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'swerv_soc_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/_Code/verilog/interface_lab/RVfpga_SoC_lab7_example/RVfpga_SoC.srcs/sources_1/bd/swerv_soc/ip/swerv_soc_axi_gpio_0_1/swerv_soc_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'swerv_soc_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/_Code/verilog/interface_lab/RVfpga_SoC_lab7_example/RVfpga_SoC.srcs/sources_1/bd/swerv_soc/ip/swerv_soc_axi_gpio_0_1/swerv_soc_axi_gpio_0_1.xci
# IP: The module: 'swerv_soc_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/_Code/verilog/interface_lab/RVfpga_SoC_lab7_example/RVfpga_SoC.srcs/sources_1/bd/swerv_soc/ip/swerv_soc_axi_gpio_0_1/swerv_soc_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'swerv_soc_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/_Code/verilog/interface_lab/RVfpga_SoC_lab7_example/RVfpga_SoC.srcs/sources_1/bd/swerv_soc/ip/swerv_soc_axi_gpio_0_1/swerv_soc_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'swerv_soc_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/_Code/verilog/interface_lab/RVfpga_SoC_lab7_example/RVfpga_SoC.srcs/sources_1/bd/swerv_soc/ip/swerv_soc_axi_gpio_0_1/swerv_soc_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'swerv_soc_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
